### ISSUE TITLE
Static site cannot be generated

### ISSUE THREAD

**Issue by kbulte** [vuestorefront/vue-storefront-1#368]
## Current behavior
I am using vuestorefront version 1.12.0 with capybara theme. I am able to run the site via the dev script. However I wanted to generate vuestorefront as a static site so I can host it via a CDN. When I execute the following commands:

`yarn build`

`yarn generate all`

I get the following typescript errors:

![image](https://user-images.githubusercontent.com/1887008/84317559-4247ad00-ab6d-11ea-84a6-059c261bc52b.png)

## Expected behavior
A folder with the name 'static' is generated and this folder contains the rendered index.html and product pages.

## Steps to reproduce the issue
1. Clone Vuestorefront 1.12.0
1. Install the Capybara theme
1. build the project by executing yarn build
1. generate a static version by executing yarn generate all

## Repository
https://github.com/DivanteLtd/vue-storefront/blob/master/core/scripts/generate.ts

## Environment details
VS code: 1.46.0
OS: macOS catalina 10.15.5
Node: 14.2.9
Yarn: 1.22.4
Typescript: 3.9.4
Vuestorefront: 1.12.0
Capybara theme: 1.0.1

**Comment by saraElsanan** [comment]
I have the same Problem ... Any solutions yet ?

**Comment by Fifciu** [comment]
VSF1 is not supporting static site generation anymore and is not going to.

**Comment by martijnvdbrug** [comment]
Hi @Fifciu! 

Is there any update on this? I see VSF2 is out now, but [I don't think SSG is supported yet](https://docs.vuestorefront.io/v2/faq/ssg.html).

With my company [Pinelab](https://github.com/Pinelab-studio) I am building most of my storefronts as static sites using Vendure. I see there already is an integration available for Vendure.

We are currently maintaining our own Vue e-commerce components, but I'd rather contribute to Vue Storefront. 
But, I really prefer SSG for most of our storefronts.

How much effort would it require to support SSG? Is it days, weeks, months? Maybe I can contribute.

**Comment by ymaheshwari1** [comment]
> SSG

As VSF1 will only support security fixes, any new functionality will not be supported in VSF1, but if you want to use VSF2 then you can create an issue on VSF2, for the same.

**Comment by martijnvdbrug** [comment]
Oops... Will do, I only see now that this is the VSF1 repo!
